spring:
  profiles:
    active: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/lorby
    username: postgres
    password: pass1234!
    driver-class-name: org.postgresql.Driver

  mail:
    host: smtp.gmail.com
    port: 587
    username: lorbylorby24@gmail.com
    password: jfmwceimsbeulthh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

