spring:
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: true
    defer-datasource-initialization: true
    show-sql: true
  logging:
    level:
      org:
        springframework:
          security: debug
      sql: debug
  main:
    banner-mode: off
  datasource:
    url: ${JDBC_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL}
    password: ${GMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
#  flyway:
#    baseline-on-migrate: true
#    enabled: true
#    user: ${DATABASE_USERNAME}
#    password: ${DATABASE_PASSWORD}
#    baseline-description: "init"
#    baseline-version: 0
#    locations: classpath:db/migration

sql:
  init:
    mode: always